### ISSUE TITLE
TypeError while running preprocess.py

### ISSUE THREAD

**Issue by nursyahr** [fahadahaf/chromir#2]
Dear authors, 

I am replicating the analysis on my cell lines of interest and have made my own list of IR events. Could I confirm if the structure of the files are correct? I get the following error:
```python
Traceback (most recent call last):
  File "preprocess.py", line 161, in <module>
    main()
  File "preprocess.py", line 150, in main
    result = create_dataset(IRdata, intragenicDHSs, load_from_file=False, save_data=True, remove_duplicates=True)
  File "preprocess.py", line 85, in create_dataset
    pos_data_V1 = remove_overlap_duplicates(pos_data_V1)
  File "preprocess.py", line 54, in remove_overlap_duplicates
    final = [data[0,1:].tolist()]
TypeError: list indices must be integers or slices, not tuple
```
I am using numpy version v1.17.2.

[20230418_Basset_all_DHSs_intragenic_modified.bed.gz](https://github.com/fahadahaf/chromir/files/11267755/20230418_Basset_all_DHSs_intragenic_modified.bed.gz)
[20230418_COAD_diffIR.txt](https://github.com/fahadahaf/chromir/files/11267756/20230418_COAD_diffIR.txt)

**Comment by fahadahaf** [comment]
Hi,
I have updated and fixed the `preprocess.py` script, you shouldn't be seeing that error anymore.  
In your IR data files, make sure to include parentheses in the coordinates of exons and introns, for example: `(500,545)`.

**Comment by nursyahr** [comment]
Hi Fahad,

Thank you! I have managed to successfully run the script :)
